mozilla-platform-ops/relops_infra_as_code

- terraform/base/outputs.tf
add link to canonical source as well
> add latest vpn netblocks

- terraform/grafana/terraform.tfvars
https://github.com/grafana/grafana/releases
* a few security issues were fixed
* misc panel fixes/updates
> upgrade grafana to 6.1.6

- terraform/vault/ecs-cluster.tf
- terraform/vault/lb.tf
- terraform/vault/task-definitions/vault.json
- terraform/vault/terraform.tfvars
- tighten up the security groups
- bump the vault version to 1.1.3
- update to latest ecs ami
https://bugzilla.mozilla.org/show_bug.cgi?id=1530501
> Vault changes

- terraform/base/tf_state_lock_sops_codecommit.tf
- terraform/sops_codecommit/backend.tf
- terraform/sops_codecommit/codecommit.tf
- terraform/sops_codecommit/kms.tf
- terraform/sops_codecommit/providers.tf
- terraform/sops_codecommit/resources.tf
- terraform/sops_codecommit/terraform.tfvars
- terraform/sops_codecommit/variables.tf
https://bugzilla.mozilla.org/show_bug.cgi?id=1565112
> New relops sops code commit repo

- terraform/telegraf/ecs-cluster.tf
- terraform/telegraf/lb.tf
- terraform/telegraf/terraform.tfvars
- terraform/telegraf/vars.tf
@dividehex this updates the security group change I added for telegraf to receive github service/status webhooks
> Telegraf webhooks

- terraform/vault/lb.tf
- terraform/vpns/use1.tf
- terraform/vpns/usw2.tf
This removes the vpns to macstadium and the vault lb access
> Revert macstadium vpn and vault lb changes

- terraform/base/tf_state_lock_vault_config.tf
- terraform/providers.tf
- terraform/vault_config/README.md
- terraform/vault_config/auth_backends.tf
- terraform/vault_config/backend.tf
- terraform/vault_config/policies/admin.hcl
- terraform/vault_config/policies/hiera_admin.hcl
- terraform/vault_config/policies/puppet_role_template.hcl.tpl
- terraform/vault_config/policy.tf
- terraform/vault_config/providers.tf
- terraform/vault_config/puppet_approle_ids.tf
- terraform/vault_config/resources.tf
- terraform/vault_config/secret_backends.tf
- terraform/vault_config/terraform.tfvars
- terraform/vault_config/variables.tf
- terraform/vault_config/vault_provider.tf
- tests/runtests.sh
This code manages configurations within vault sans any secrets data
> Vault config code

- .travis.yml
> Update travis notifications

- .travis.yml
This should fix the broken tests.
> Update tests to use terraform v0.12.24

- terraform/vault/terraform.tfvars
This updates the launch config to use the latest ecs optimized ami with the latest ecs agent.  Once the config is update, a manual instance refresh can be initiated in the AWS dashboard.
> Use latest ec2 ami

- terraform/vault/terraform.tfvars
This upgrades the ECS instances to the latest ami.
> [vault] upgrade vault ecs ami to latest

- terraform/maas/lb.tf
- terraform/maas/rackd_vms.tf
- terraform/maas/regional_ec2.tf
- terraform/maas/terraform.tfvars
- terraform/maas/vars.tf
This was work I had done before going on Leave and just needs to be landed to converge.
> [maas] add rackd to test.releng.mdc1, remove mdc2 rackd

- terraform/telegraf/certificates.tf
- terraform/telegraf/datasources.tf
- terraform/telegraf/ecs-cluster.tf
- terraform/telegraf/ecs-queues.tf
- terraform/telegraf/ecs-task-exec-role.tf
- terraform/telegraf/ecs-vcs.tf
- terraform/telegraf/ecs-workers.tf
- terraform/telegraf/lb.tf
- terraform/telegraf/terraform.tfvars
- terraform/telegraf/vars.tf
waiting on on https://github.com/mozilla-platform-ops/relops_infra_as_code/pull/48
> Bug1664040 telegraf handle tc timestamp change

- terraform/base/.terraform.lock.hcl
- terraform/base/versions.tf
- terraform/bitbar-devicepool/.terraform.lock.hcl
- terraform/bitbar-devicepool/gce-providers.tf
- terraform/bitbar-devicepool/versions.tf
- terraform/maas/.terraform.lock.hcl
- terraform/maas/certificates.tf
- terraform/maas/versions.tf
- terraform/providers.tf
- terraform/puppetagain_ca_codecommit/.terraform.lock.hcl
- terraform/puppetagain_ca_codecommit/versions.tf
- terraform/ronin-puppet-package-repo/.terraform.lock.hcl
- terraform/ronin-puppet-package-repo/versions.tf
- terraform/sops_codecommit/.terraform.lock.hcl
- terraform/sops_codecommit/versions.tf
- terraform/taskqueue-influxdb-metrics/.terraform.lock.hcl
- terraform/taskqueue-influxdb-metrics/versions.tf
- terraform/telegraf/.terraform.lock.hcl
- terraform/telegraf/certificates.tf
- terraform/telegraf/versions.tf
- terraform/vault/.terraform.lock.hcl
- terraform/vault/certificates.tf
- terraform/vault/versions.tf
- terraform/vault_config/.terraform.lock.hcl
- terraform/vault_config/vault_provider.tf
- terraform/vault_config/versions.tf
- terraform/vpns/.terraform.lock.hcl
- terraform/vpns/versions.tf
- terraform/vsphere_provider.tf
This PR brings each project and its state up to version 0.14
> Tf upgrade 0.14

- .circleci/config.yml
- README.md
- add config
- add badge to readme
> add circleci config

- terraform/vault/lb.tf
Part of removing the jumphosts.
> Allow corp vpn to reach vault endpoint

- terraform/azure_ad/azuread_provider.tf
- terraform/azure_ad/service_principals.tf
This PR contains the required AD applications and service principals needed for the FXCI dev/test sub.
> Azure apps and service principals

- terraform/vault/task-definitions/vault.json
- terraform/vault/terraform.tfvars
This PR updates both the vault docker image and the ecs ami to the latest.
> Update vault to 1.7.0

- terraform/base/outputs.tf
- terraform/base/vpc.tf
- terraform/vault/datasources.tf
- terraform/vault/ecs-cluster.tf
- terraform/vault/ecs-service.tf
- terraform/vpns/use1.tf
- terraform/vpns/usw2.tf
This PR re-divides the vpc cidrs to include private and public subnets.  It also moves vault to the private subnets.
> Add private subnets

- terraform/base/iam_users.tf
I've imported the existing users to be managed.  AJVB is being added.  This does not manage group membership or policy attachment.
> [base] Add user management to base

- simplemdm/m1_mdm_naming.sh
- simplemdm/nameit.sh
not perfect, but what I made+used today to move the m1's into the m1 group and rename them
checks serial number from host through ssh
queries simplemdm with serial number
sets device_name=hostname, and group
> m1 naming scripts

- terraform/azure_fxci/local-variables.tf
- terraform/azure_fxci/rg-central-us-runbooks.tf
- terraform/azure_fxci/runbooks/nv6_audit_delete.ps1
In addition to the runbook pre-commit picked up on some linting.
> relops_231 - delete old NV6 VMs

- terraform/azure_fxci/local-variables.tf
- terraform/azure_fxci/rg-central-us-runbooks.tf
- terraform/azure_fxci/runbooks/nv6_audit_delete.ps1
* relops_231 - delete old NV6 VMs
* relops_231 - Add runbook to delete old NV6 VMs
> relops_231 - delete old NV6 VMs (#111)

- terraform/azure_fxci/local-variables.tf
us-west-2 resources were missing. Applied without error.
> add us-west-2 for level 1 and 2 builder resources

- terraform/azure_trusted_fxci/local-variables.tf
> Add trusted us west 2 to terraform

- terraform/gcp-fxci-production-level1-workers/gcp_iam.tf
Already applied.
See https://mozilla-hub.atlassian.net/browse/RELOPS-918.
> fxci-l1: grant bhearsum simulation perms

- terraform/gcp-fxci-production-level1-workers/README.md
- terraform/gcp-fxci-production-level1-workers/terraform.tfvars
Add read-only rights for more releng users (per https://mozilla-hub.atlassian.net/browse/RELOPS-953).
Already `tf apply`-ied.
> fxci l1: add more releng users

- terraform/base/tf_state_lock_gcp-fxci-production-level3-workers.tf
- terraform/base/vpc.tf
- terraform/gcp-fxci-production-level1-workers/_monitoring_viewer.tf
- terraform/gcp-fxci-production-level3-workers/.terraform.lock.hcl
- terraform/gcp-fxci-production-level3-workers/_gcp_provider.tf
- terraform/gcp-fxci-production-level3-workers/_monitoring_viewer.tf
- terraform/gcp-fxci-production-level3-workers/backend.tf
- terraform/gcp-fxci-production-level3-workers/providers.tf
- terraform/gcp-fxci-production-level3-workers/resources.tf
- terraform/gcp-fxci-production-level3-workers/terraform.tfvars
- terraform/gcp-fxci-production-level3-workers/variables.tf
See https://mozilla-hub.atlassian.net/browse/RELOPS-984.
> l1 and l3 fxci gcp: add monitoring viewer role to svc account

- terraform/gcp-fxci-production-level1-workers/_compute_read_only_access.tf
- terraform/gcp-fxci-production-level1-workers/_tech_support_editor.tf
- terraform/gcp-fxci-production-level1-workers/_vars.tf
- terraform/gcp-fxci-production-level3-workers/_tech_support_editor.tf
- terraform/gcp-fxci-production-level3-workers/_vars.tf
- terraform/gcp-fxci-production-level3-workers/terraform.tfvars
See https://mozilla-hub.atlassian.net/browse/RELOPS-532.
> RELOPS-532: add tech support editor role for releng

- terraform/gcp-fxci-production-level3-workers/_compute_read_only_access.tf
- terraform/gcp-fxci-production-level3-workers/_vars.tf
- terraform/gcp-fxci-production-level3-workers/terraform.tfvars
Add L3 read-only access for releng and a few other users.
Already `tf apply`ied.
See https://mozilla-hub.atlassian.net/browse/RELOPS-916.
> add l3 r/o access

- terraform/gcp-taskcluster-imaging/_vars.tf
- terraform/gcp-taskcluster-imaging/terraform.tfvars
See https://mozilla-hub.atlassian.net/browse/RELOPS-1080.
> add computeUser IAM perms for releng, translations, and ee folk

- docker/relsre-metrics-prom-docker/README.md
- **readme: fix ordering**
- **readme: remove comment**
> feat(relsre-metrics-prom-docker): prom k8s errata

- docker/relsre-metrics-prom-docker-android/Dockerfile
- docker/relsre-metrics-prom-docker-android/README.md
- docker/relsre-metrics-prom-docker-android/docker_build
- docker/relsre-metrics-prom-docker-android/docker_run
- docker/relsre-metrics-prom-docker-android/entrypoint.sh
- docker/relsre-metrics-prom-docker-android/etc/common.sh
- docker/relsre-metrics-prom-docker-android/etc/startup.sh
- docker/relsre-metrics-prom-docker-android/etc/telegraf_android.conf
See https://mozilla-hub.atlassian.net/browse/RELOPS-1124.
Docker image that runs scripts to collect information about TC-integrated Bitbar Android HW devices.
> relsre-metrics-prom-docker-android

- packer/mac/README.md
- packer/mac/tester14/builder.sh
- packer/mac/tester14/vault-fake.yaml
- packer/mac/tester15/builder.sh
- packer/mac/tester15/vault-fake.yaml
https://mozilla-hub.atlassian.net/browse/RELOPS-1331
> [RELOPS-1331] Provide fake vault file for Mac VM builder

- packer/mac/scripts/README.md
- packer/mac/scripts/host_provisioner.sh
check for `GOOGLE_APPLICATION_CREDENTIALS` earlier in script and added a `readme.md`
> check for cred sooner and create readme.md

- packer/mac/scripts/host_provisioner.sh
https://mozilla-hub.atlassian.net/browse/RELOPS-1386
Checked for the OCI key sooner and fixed issue where vm's would have the same serial/MAC
> [RELOPS-1386] add tart clone step and reorder cred check

- packer/mac/scripts/README.md
- packer/mac/scripts/orbit.py
Work in progress but the basic functionality is there
> [RELOPS-1398] VM Management Tool

- packer/mac/tester15/create-base.pkr.hcl
- packer/mac/tester15/disable-sip.pkr.hcl
Details: https://mozilla-hub.atlassian.net/browse/RELOPS-1457
> [RELOPS-1457] macOS15 VM builder bugfix
