terraform/grafana/certificates.tf
terraform/grafana/datasources.tf
terraform/grafana/ecs-cluster.tf
terraform/grafana/ecs-task-exec-role.tf
terraform/grafana/lb.tf
terraform/grafana/mysql.tf
terraform/grafana/terraform.tfvars
terraform/grafana/vars.tf

These terraform configs set up a simple public grafana service.
It consists of a dedicated ecs cluster w/single fargate task, a
load balanace with an attached dns mozops.net record and
corresponding ssl cert.  It also sets up a multi-az mysql rds
instance for the application backend.  Container secrets are
store and curated by hand in ssm parameter store.

Grafana project

---

terraform/grafana/ecs-task-exec-role.tf
terraform/grafana/terraform.tfvars

Switch task exec role to trust ecs-task and not ec2. The current deploy is runing with this applied.

Grafana update

---

terraform/taskqueue-influxdb-metrics/function.py

IT says it's OK to go to 14 vs 7 log lines per minute.
Tested locally. Working in AWS.

taskqueue-influxdb-metrics: add new bitbar g-w queues

---

terraform/base/tf_state_lock_telegraf.tf
terraform/telegraf/backend.tf
terraform/telegraf/certificates.tf
terraform/telegraf/cloudwatch-log-group.tf
terraform/telegraf/datasources.tf
terraform/telegraf/ecs-cluster.tf
terraform/telegraf/ecs-task-exec-role.tf
terraform/telegraf/lb.tf
terraform/telegraf/providers.tf
terraform/telegraf/resources.tf
terraform/telegraf/terraform.tfvars
terraform/telegraf/variables.tf
terraform/telegraf/vars.tf

Set up an ECS service running telegraf:
1. to receive influx formatted metrics posts as a relay, and
2. to perform metrics queries through other input plugins.
This is a copy the grafana terraform setup, with the port, container, role, and variables changed. I'm using a container image pushed to ECR. I will add that in a separate PR

Telegraf service

---

terraform/bitbar-devicepool/compute.tf

- n1-standard-2: 2 CPU, 8 GB RAM
- 25GB spinning disk
- disks aren't deleted on node deletion (allows resizing without losing the disk)

bitbar devicepool uses larger nodes

---

terraform/grafana/ecs-cluster.tf
terraform/grafana/lb.tf
terraform/grafana/terraform.tfvars
terraform/grafana/vars.tf

* upgrade to grafana 6.2.5 (confirmed available on docker hub)
* make the fqdn a variable
* use fqdn to set domain for grafana config (so it can tell us where it is in alerts)

fqdn var, set in config

---

terraform/grafana/ecs-cluster.tf
terraform/grafana/terraform.tfvars
terraform/grafana/vars.tf

https://github.com/mozilla-platform-ops/relops_infra_as_code/pull/19 helped, but the URLs in Pagerduty alerts are still wrong:
```
http://grafana.relops.mozops.net:3000/d/eX_tJyuiz/android-queues?fullscreen&edit&tab=alert&panelId=10&orgId=1
```
I think we want to set root_url.

grafana: set root_url

---

terraform/base/policies/PytestServicesReadOnly.json

Will allow pytest-services to run it's new "check if EBS snapshots are public" test:
https://github.com/mozilla-services/pytest-services/pull/285
cc @dividehex

Give pytest role read perms for ebs snapshots

---

.travis.yml

* Move slack notifications to #relops-bots
* Removes deprecated keys/values `sudo:false` and `lang:bash`
* Slight alteration to notification template

Change travis slack channel notifications

---

.pre-commit-config.yaml
terraform/vault/task-definitions/vault.json
terraform/vault_config/puppet_approle_ids.tf

This PR does the following:
* updates pre-commit checks to latest versions
* expands puppet approle boundaries (this is a noop since the approles were originally created with these boundaries)
* bumps the vault docker image version to the latest (v1.5.3)

Bump vault version

---

terraform/telegraf/certificates.tf
terraform/telegraf/datasources.tf
terraform/telegraf/ecs-cluster.tf
terraform/telegraf/ecs-queues.tf
terraform/telegraf/ecs-task-exec-role.tf
terraform/telegraf/ecs-vcs.tf
terraform/telegraf/ecs-workers.tf
terraform/telegraf/lb.tf
terraform/telegraf/terraform.tfvars
terraform/telegraf/vars.tf

The current telegraf cluster in ECS has this config, separate services for:
telegraf relay (influx and webhooks) to influx
telegraf_workers checking worker states
telegraf_queues checking queue levels
telegraf_vcs checking treestatus, m-c commits, releases (chrome, ff)
We moved to this when the requests to the TC api's began timing-out and coming back more slowly in __(July? well, some months ago). This reduces the number of api calls from 4 duplicate tasks hitting all of these, on different offsets, and I increased the timeouts in the same changes. We get fewer datapoints, but we reduced traffic to the api and are more likely to get some data with the long timeouts.

telegraf relay separated from queue/polling

---

terraform/vault_config/puppet_approle_ids.tf

This PR simply adds a new vault approle mapped to the puppet role `gecko_t_osx_1015_r8_qa`

[vault_config] add approle for gecko_t_osx_1015_r8_qa

---

terraform/vault_config/audit.tf
terraform/vault_config/puppet_approle_ids.tf

This PR enables audit logs in vault which are then routed from dockers to cloudwatch

Enable vault audit to cloudwatch

---

terraform/vault/cloudwatch.tf
terraform/vault/ecs-task-def.tf
terraform/vault/task-definitions/vault.json

This PR creates a cloudwatch log group and turns on the awslogs driver in the vault docker containers.

[vault] Vault log to cloudwatch

---

.circleci/config.yml
.travis.yml
terraform/azure_ad/versions.tf
terraform/azure_fxci/resource_groups.tf
terraform/azure_fxci/rg-central-us-gecko-t.tf
terraform/azure_fxci/rg-east-us-2-gecko-t.tf
terraform/azure_fxci/rg-east-us-gecko-t.tf
terraform/azure_fxci/rg-north-central-us-gecko-t.tf
terraform/azure_fxci/rg-packer-through-cib.tf
terraform/azure_fxci/rg-south-central-us-gecko-t.tf
terraform/azure_fxci/rg-taskcluster-worker-manager-production.tf
terraform/azure_fxci/rg-taskcluster-worker-manager-staging.tf
terraform/azure_fxci/rg-west-us-2-gecko-t.tf
terraform/azure_fxci/rg-west-us-gecko-t.tf
terraform/azure_fxci/versions.tf
terraform/base/versions.tf
terraform/bitbar-devicepool/versions.tf
terraform/puppetagain_ca_codecommit/versions.tf
terraform/ronin-puppet-package-repo/versions.tf
terraform/sops_codecommit/versions.tf
terraform/taskqueue-influxdb-metrics/versions.tf
terraform/telegraf/ecs-cluster.tf
terraform/telegraf/versions.tf
terraform/vault/cloudwatch.tf
terraform/vault/dynamodb.tf
terraform/vault/ecs-cluster.tf
terraform/vault/ecs-task-def.tf
terraform/vault/versions.tf
terraform/vault_config/versions.tf
terraform/vpns/versions.tf

This PR updates all of the projects to be compliant with, and require, Terraform >= v0.15.x.

Upgrade to 0.15

---

terraform/vpns/use1.tf
terraform/vpns/usw2.tf

These tunnels were missed on the MDC2 decomm.  This simply rips out the aws side of the infra. ⚰️ RIP

Remove defunct mdc2 vpns

---

terraform/vault/.terraform.lock.hcl
terraform/vault/ecs-cluster.tf
terraform/vault/ecs-task-def.tf
terraform/vault/task-definitions/vault.json
terraform/vault/terraform.tfvars
terraform/vault/vars.tf

This PR is a refactor of vault to use the launch template instead of a launch configuration.  This allow the use of automatic scaling group instance refresh then the template changes which removes the need to manually call a refresh after updating the ami id.
This also:
- updates the aws provider to latest
- fixes some resource tagging
- moves the docker version to a terraform variable

[vault] refactor autoscaling group to launch template

---

terraform/azure_ad/sp_puppet_test_kitchen.tf

Adds a application and service principal for puppet test kitchen use in circleCI.  Secrets have been copied over and stored in circleCI secret context space.

Application and service principal for puppet test kitchen

---

terraform/azure_fxci/gecko-1-resources.tf
terraform/azure_fxci/gecko-3-resources.tf
terraform/azure_fxci/local-variables.tf

The Azure resources gecko-1 and gecko-3 are not created within terraform. This PR resolves [RELOPS-248](https://mozilla-hub.atlassian.net/browse/RELOPS-248) by adding those resources to terraform.

add gecko-1 & gecko-3 resources to tf

---

terraform/base/.terraform.lock.hcl
terraform/base/tf_state_lock_ronin-puppet-assets.tf
terraform/ronin-puppet-assets/.terraform.lock.hcl
terraform/ronin-puppet-assets/backend.tf
terraform/ronin-puppet-assets/gcloud_provider.tf
terraform/ronin-puppet-assets/gcloud_storage.tf
terraform/ronin-puppet-assets/providers.tf
terraform/ronin-puppet-assets/resources.tf
terraform/ronin-puppet-assets/variables.tf

Already `tf apply`'d.
See https://mozilla-hub.atlassian.net/browse/RELOPS-217.

add GCP linux ronin puppet assets bucket

---

terraform/azure_fxci/devloaner-resources.tf
terraform/azure_fxci/devtest-resources.tf
terraform/azure_fxci/local-variables.tf

Terraform plan:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
+ create
Terraform will perform the following actions:
+ resource "azurerm_network_security_group" "devtest" {
+ id                  = (known after apply)
+ location            = "centralus"
+ name                = "nsg-central-us-devtest"
+ resource_group_name = "rg-central-us-devtest"
+ security_rule       = (known after apply)
+ tags                = {
+ "Name"             = "central-us-devtest"
+ "owner_email"      = "mcornmesser@mozilla.com"
+ "production_state" = "production"
+ "project_name"     = "azure_fxci"
+ "source_repo_url"  = "https://github.com/mozilla-platform-ops/relops_infra_as_code"
+ "terraform"        = "true"
} …
```

Add resources for joel/testers to test new images

---

terraform/azure_ad/sp_taskcluster_worker_managers.tf

Fix copy and paste error to give taskcluster-worker-manager-staging contributor access. 
However, had to manually add it through the UI. Trying to apply the Terraform code leads to: 
```
│ Error: Error: Resource Group "Puppet-Test-Kitchen" was not found
│
│   with data.azurerm_resource_group.puppet_test_kitchen_rg,
│   on sp_puppet_test_kitchen.tf line 5, in data "azurerm_resource_group" "puppet_test_kitchen_rg":
│    5: data "azurerm_resource_group" "puppet_test_kitchen_rg" {
```
I am not sure what has changed there.

fix copy and paste error

---

terraform/azure_fxci/rg-central-us-runbooks.tf
terraform/azure_fxci/runbooks/worker_scanner_helper.ps1

The nv6 runbook is no longer needed. 
Do not attempt to remove public IPs in the worker-manager helper script. Public IPs are no longer provisioned. Commented out if in case this changes int he future. 
Applied without error.

unschedule nv6 runbook.

---

terraform/azure_ad/sp_packer_worker_images.tf

Plan output:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
+ create
Terraform will perform the following actions:
+ resource "azuread_application" "worker_images_dev" {
+ app_role                = (known after apply)
+ application_id          = (known after apply)
+ display_name            = "worker_images_dev"
+ homepage                = "https://github.com/mozilla-platform-ops/worker-images"
+ id                      = (known after apply)
+ identifier_uris         = (known after apply)
+ name                    = (known after apply)
+ oauth2_permissions      = (known after apply)
+ object_id               = (known after apply)
+ owners                  = [
+ …
```

Create azure service principal for use with packer

---

terraform/azure_fx_nonci/worker-images.tf

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
+ create
Terraform will perform the following actions:
+ resource "azurerm_shared_image" "win10_64_2009_alpha" {
+ gallery_name        = "workerimages"
+ hyper_v_generation  = "V2"
+ id                  = (known after apply)
+ location            = "centralus"
+ name                = "win10-64-2009-alpha"
+ os_type             = "Windows"
+ resource_group_name = "rg-packer-worker-images"
+ identifier {
+ offer     = "Windows-10"
+ publisher = "MicrosoftWindowsDesktop"
+ sku       = "win10-22h2-avd"
}
}
+ resource "azurerm_shared_image" "win11_64_2009_alpha" {
+ gallery_name        = "workerimages"
+ hyper_v_generation  = "V2"
+ id …
```

Add more shared image gallery definitions

---

.pre-commit-config.yaml
docker/dockerfiles/circleci-ubuntu-2204/Dockerfile
docker/dockerfiles/circleci-ubuntu-2204/README.md

Create new 22.04 image used in CI. Used in https://github.com/mozilla-platform-ops/snakepit_puppet/pull/8 initially.
Published at https://hub.docker.com/repository/docker/mozillarelops/circleci-ubuntu-2204.

circleci docker image update

---

terraform/base/tf_state_lock_gcp-fxci-production-level1-workers.tf
terraform/create_state.sh
terraform/gcp-fxci-production-level1-workers/.terraform.lock.hcl
terraform/gcp-fxci-production-level1-workers/README.md
terraform/gcp-fxci-production-level1-workers/backend.tf
terraform/gcp-fxci-production-level1-workers/gcp_iam.tf
terraform/gcp-fxci-production-level1-workers/gcp_provider.tf
terraform/gcp-fxci-production-level1-workers/providers.tf
terraform/gcp-fxci-production-level1-workers/resources.tf
terraform/gcp-fxci-production-level1-workers/terraform.tfvars
terraform/gcp-fxci-production-level1-workers/variables.tf

Has been applied at [bc46f58](https://github.com/mozilla-platform-ops/relops_infra_as_code/pull/147/commits/bc46f58727b8a59930353e28180a5e53150a0793) and [7c1be58](https://github.com/mozilla-platform-ops/relops_infra_as_code/pull/147/commits/7c1be58cef13e2f5e956d23b0af3c94dda5df10a) already. Releng and translations have verified access.
Also:
- create_state.sh creates a terraform.tfvars file now.

tf: fxci production level1 workers: add permissions for releng and translations

---

terraform/gcp-fxci-production-level1-workers/gcp_iam.tf

bhearsum is debugging something and this role would be useful. 
Seems to be within the intent of the RRA we've already done for allowing access to l1 GCP console for releng and translations.
Already applied.

gcp l1: add logging.viewer for releng and translations

---

.github/workflows/pre-commit.yaml

I noticed a warning on https://github.com/mozilla-platform-ops/relops_infra_as_code/actions/runs/8837321346.
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v3, hashicorp/setup-terraform@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

upgrade actions

---

terraform/gcp-fxci-production-level1-workers/_compute_read_only_access.tf
terraform/gcp-fxci-production-level1-workers/_compute_simulate_maintenance_events.tf
terraform/gcp-fxci-production-level1-workers/terraform.tfvars

Rework this module based on comments in https://github.com/mozilla-platform-ops/relops_infra_as_code/pull/164#pullrequestreview-2056208644 and general usability.
- rename files with _ to help identifying the non-templated files in a module
- rename files to indicate what they do
- move bhearsum's compute maintenance event simulation rights to separate file
- move mcastelluccio and jmaher to a non-releng group to avoid future confusion
- add read only rights for this new group
Already terraform applied.

refactor pr #164, clarify non-membership of some users

---

terraform/azure_ad/sp_ms_store_apitoken_app.tf

Create app to be used in MS Partner Center to generate store API tokens. The app should have no rights within Entra and will be assigned rights within the Partner Center.

Create Entra App to be used in Partner Center

---

.github/workflows/pre-commit.yaml
.pre-commit-config.yaml

Add a tool I wrote (https://github.com/mozilla-platform-ops/tf_authoritative_scanner) to detect authoritative Terraform module usage and fail tests on it.
Example interactive use (just as an example, it's normally run by pre-commit):
```bash
powderdry  relops_infra_as_code git:(9d28089) ✗  ➜  tfas --version
1.0.4
powderdry  relops_infra_as_code git:(9d28089) ✗  ➜  git show -q
commit 9d280890d4ee7ff702ece203729e6722f4600aa1 (HEAD)
Date:   Mon Jul 22 16:36:55 2024 -0400
...
powderdry  relops_infra_as_code git:(9d28089) ✗  ➜  tfas .
AUTHORITATIVE: ./terraform/gcp-fxci-production-level1-workers/github_oidc.tf:10: resource "google_project_iam_binding" "compute_admin" {
AUTHORITATIVE: ./terraform/gcp-fxci-production-level3-workers/github_oidc.tf:10: resource "google_project_iam_binding" …
```

add terraform authoritative scanner

---

packer/mac/scripts/host_provisioer.sh

Summary:
This PR fully automates the setup of macOS CI machines, ensuring they can:
✅ Install Google Cloud SDK (gcloud) non-interactively
✅ Authenticate with a service account & configure Artifact Registry
✅ Pull macOS VM images from GCP using Tart
✅ Download & install Cilicon from S3
✅ Generate a cilicon.yaml config file in the user’s home directory
✅ Launch Cilicon automatically after setup
🔹 Key Changes
•	Added `host_provisioner.sh`
•	Installs `gcloud` if missing (non-interactively)
•	Authenticates with GCP using service account credentials
•	Configures `gcloud auth` for Artifact Registry
•	Verifies and pulls Tart VM images from GCP
•	Downloads & extracts Cilicon-3.zip to `/Applications`
•	Creates a `cilicon.yaml` config in the user’s home directory
•	Launches Cilicon.app via Terminal …

Automate Tart CI Setup & Cilicon Deployment

---

packer/mac/tester14/vault-fake.yaml

Noticed a VM worker had the old config.  Doesn't functionally matter as they're 'dummy' vm's but just updating for consistency/clarity. This changes the fake key used to build worker vm's that are not plumbed into Taskcluster.

Change fake key vm pool config from 14 to 15

---

osx_pkg_blueprints/README.md
osx_pkg_blueprints/p_role_gecko_t_osx_1400_r8/.gitignore
osx_pkg_blueprints/p_role_gecko_t_osx_1400_r8/build-info.plist
osx_pkg_blueprints/p_role_gecko_t_osx_1400_r8/payload/etc/puppet_role
osx_pkg_blueprints/p_role_gecko_t_osx_1400_r8_staging/.gitignore
osx_pkg_blueprints/p_role_gecko_t_osx_1400_r8_staging/build-info.plist
osx_pkg_blueprints/p_role_gecko_t_osx_1400_r8_staging/payload/etc/puppet_role
osx_pkg_blueprints/p_role_gecko_t_osx_1500_m4/.gitignore
osx_pkg_blueprints/p_role_gecko_t_osx_1500_m4/build-info.plist
osx_pkg_blueprints/p_role_gecko_t_osx_1500_m4/payload/etc/puppet_role
osx_pkg_blueprints/p_role_gecko_t_osx_1500_m4_staging/.gitignore
osx_pkg_blueprints/p_role_gecko_t_osx_1500_m4_staging/build-info.plist
osx_pkg_blueprints/p_role_gecko_t_osx_1500_m4_staging/payload/etc/puppet_role
osx_pkg_blueprints/scripts/sign.sh

https://mozilla-hub.atlassian.net/browse/RELOPS-591
We’re beginning the process of improving macOS provisioning by introducing `/etc/puppet_role` as a way to bootstrap Puppet configuration automatically.
Currently, mac deployments rely exclusively on Puppet via Bolt for post-provision configuration. By landing a simple, signed `.pkg` that writes the appropriate role to `/etc/puppet_role`, we can enable Macs to auto-puppetize on first boot or MDM enrollment.
These .pkg files will be built using [munkipkg](https://github.com/munki/munki-pkg), signed with our Developer ID Installer certificate, and uploaded to MDM for distribution as part of the initial software payload.

[RELOPS-591] add osx package blueprints for packages to deliver /etc/puppet_role
